---
exclude: ^alembic$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        - id: check-ast
        - id: check-builtin-literals
        - id: check-case-conflict
        - id: check-executables-have-shebangs
        - id: check-json
        - id: check-merge-conflict
        - id: check-shebang-scripts-are-executable
        - id: check-symlinks
        - id: check-toml
        - id: check-yaml
        - id: check-xml
        - id: debug-statements
        - id: destroyed-symlinks
        - id: fix-byte-order-marker
        - id: mixed-line-ending
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-vcs-permalinks

    - repo: https://github.com/python-poetry/poetry
      rev: 1.8.3
      hooks:
        - id: poetry-check
          name: poetry-check[TochkaAi]
          args: [ -C, app ]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.4
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]
        - id: ruff-format
